# Generated by Django 5.0.4 on 2024-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
    ]
